/**
 * POST /api/ai/clean
 * Uses Groq LLM to enhance book metadata (SLiMS fields, cleaning title/authors)
 */

import { requireAuth } from '../../utils/auth'
import type { BookMetadata } from '../../utils/metadata/types'

// Groq API Configuration
const GROQ_API_URL = 'https://api.groq.com/openai/v1/chat/completions'
const MODEL_ID = 'llama-3.1-8b-instant' // Fast, efficient, good at JSON

interface AiCleanRequest {
  metadata: BookMetadata
}

export default defineEventHandler(async (event) => {
  await requireAuth(event)
  const { metadata } = await readBody<AiCleanRequest>(event)
  const config = useRuntimeConfig()
  const apiKey = config.groqApiKey || process.env.GROQ_API_KEY
  
  if (!apiKey) {
    throw createError({
      statusCode: 500,
      message: 'GROQ_API_KEY is not configured on server'
    })
  }
  
  // System Prompt for Library Cataloger Persona
  const systemPrompt = `You are an expert Library Cataloger and SLiMS (Senayan Library Management System) specialist.
  Your task is to enhance, correct, and complete the bibliographic metadata for a book based on the provided JSON input.
  
  Strictly follow these rules:
  1. OUTPUT FORMAT: Return ONLY a valid JSON object matching the exact structure of the input. Do not include markdown formatting (like \`\`\`json) or extra text.
  2. DATA IMPROVEMENT:
     - DDC/LCC: Estimate accurate Dewey Decimal and LC Classification call numbers if missing.
     - Subjects: Generate 3-5 relevant Library of Congress Subject Headings (semicolon separated).
     - Title: Fix capitalization (Title Case) and remove subtitles if they are erroneously in the title field.
     - Authors: Standardize format (e.g., "Lastname, Firstname" is preferred for SLiMS but maintain input consistency if unsure).
     - Physical: Estimate "collation" (e.g., "x, 300 p. ; 23 cm") if description contains page/size info.
     - SLiMS Fields: Populate 'publishPlace', 'gmd' (default 'Text'), 'classificationTrust' (set to 'Estimated' if generated by you).
  3. AI LOG: Populate the 'aiLog' array with brief notes on what you changed (e.g., "Estimated DDC", "Standardized Title").
  4. CONSISTENCY: Keep original valid data if it looks correct. Only fix obvious errors or fill gaps.`
  
  const userPrompt = JSON.stringify(metadata)
  
  try {
    console.info(`[AI] enhancing metadata for ${metadata.isbn}`)
    
    const response = await $fetch<any>(GROQ_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      body: {
        model: MODEL_ID,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        temperature: 0.1, // Low temperature for deterministic/strict output
        response_format: { type: 'json_object' }
      }
    })
    
    const content = response.choices[0]?.message?.content
    if (!content) throw new Error('Empty response from Groq')
      
    const enhancedData = JSON.parse(content)
    
    // Add metadata for tracking
    enhancedData.isAiEnhanced = true
    enhancedData.enhancedAt = new Date().toISOString()
    
    return enhancedData as BookMetadata
    
  } catch (error: any) {
    console.error('[AI] Enhancement failed:', error)
    throw createError({
      statusCode: 502,
      message: 'AI Service unavailble: ' + error.message
    })
  }
})
